// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDipY7BX8bkSB2_KP7LQk7WhFHdGZGqDBc',
    appId: '1:595199991228:web:5e1189b80c4755df911fb9',
    messagingSenderId: '595199991228',
    projectId: 'zenith-820d8',
    authDomain: 'zenith-820d8.firebaseapp.com',
    storageBucket: 'zenith-820d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3e_Lys3AuO6YJfmBwQKY5HdPSBNgoHiQ',
    appId: '1:595199991228:android:47ebd45e3d06fa98911fb9',
    messagingSenderId: '595199991228',
    projectId: 'zenith-820d8',
    storageBucket: 'zenith-820d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNUl6nstmarM3TbYUmVFXs94mpOfwI5Tk',
    appId: '1:595199991228:ios:6caebac8ce6bfdac911fb9',
    messagingSenderId: '595199991228',
    projectId: 'zenith-820d8',
    storageBucket: 'zenith-820d8.firebasestorage.app',
    iosBundleId: 'com.example.zenith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNUl6nstmarM3TbYUmVFXs94mpOfwI5Tk',
    appId: '1:595199991228:ios:6caebac8ce6bfdac911fb9',
    messagingSenderId: '595199991228',
    projectId: 'zenith-820d8',
    storageBucket: 'zenith-820d8.firebasestorage.app',
    iosBundleId: 'com.example.zenith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDipY7BX8bkSB2_KP7LQk7WhFHdGZGqDBc',
    appId: '1:595199991228:web:d300627b8f8d8bb7911fb9',
    messagingSenderId: '595199991228',
    projectId: 'zenith-820d8',
    authDomain: 'zenith-820d8.firebaseapp.com',
    storageBucket: 'zenith-820d8.firebasestorage.app',
  );
}
